# Template docker-push

# This template allows you to build and push your docker image to a Docker Hub account.
# The workflow allows running tests, code linting and security scans on feature branches (as well as master).
# The docker image will be validated and pushed to the docker registry after the code is merged to master.

# Prerequisites: $DOCKER_HUB_PASSWORD, $DOCKER_HUB_USERNAME, $DOCKER_USERNAME, $DOCKER_PASSWORD, $DOCKER_NAME_NEXTJS, $DOCKER_NAME_NGINX, $KUBERNETES_BASE64_CONFIG setup as deployment variables

#image: atlassian/default-image:2
image: node:16.16.0

definitions:
  # Article ref:
  # https://community.atlassian.com/t5/Bitbucket-questions/Container-Build-exceeded-memory-limit/qaq-p/1986822
  services:
    docker:
      memory: 2000  # up memory for docker-in-docker from 1GB to 2GB
    docker-with-large-memory:
      memory: 7000
      type: docker 

  buildImageNextjs: &buildImageNextjs
    name: Build and Push Docker Image - Front Web Nextjs
    script:
      #- rm -rf node_modules && rm package-lock.json
      - echo "Docker service with 7120 MB memory"
      #- export NODE_OPTIONS=--max-old-space-size=7120
      #- rm -rf node_modules
      #- npm cache clean --force
      #- npm install
      #- npm run build:$BITBUCKET_BRANCH 
      # Create docker URI
      - export VERSION=$BITBUCKET_BRANCH-$BITBUCKET_BUILD_NUMBER
      - export BRANCH=$BITBUCKET_BRANCH
      - export DOCKER_PUSH_URI=$DOCKER_USERNAME/$DOCKER_NAME_NEXTJS:$VERSION
      - export DOCKER_URI=$DOCKER_NAME_NEXTJS
      - export ENVIRONMENT=master
      - echo $ENVIRONMENT
      # Build the image
      - docker build --build-arg ENVIRONMENT -f deployment/DockerfileNextjs -t $DOCKER_URI .
      - echo "$DOCKER_HUB_PASSWORD" | docker login --username $DOCKER_HUB_USERNAME --password-stdin
      #- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker tag "$DOCKER_URI" "$DOCKER_PUSH_URI"
      - docker push "$DOCKER_PUSH_URI"
    size: 2x
    services: [docker-with-large-memory]      

  buildImageNginx: &buildImageNginx
    name: Build and Push Docker Image - Front Web Nginx
    script:
      #- rm -rf node_modules && rm package-lock.json
      - echo "Docker service with 7120 MB memory"
      #- export NODE_OPTIONS=--max-old-space-size=7120
      #- rm -rf node_modules
      #- npm cache clean --force
      #- npm install
      #- npm run build:$BITBUCKET_BRANCH 
      # Create docker URI
      - export VERSION=$BITBUCKET_BRANCH-$BITBUCKET_BUILD_NUMBER
      - export BRANCH=$BITBUCKET_BRANCH
      - export DOCKER_PUSH_URI=$DOCKER_USERNAME/$DOCKER_NAME_NGINX:$VERSION
      - export DOCKER_URI=$DOCKER_NAME_NGINX
      - export PROXY="difierelo-nextjs-server.development.svc.cluster.local:4200"
      - echo $PROXY
      # Build the image
      - docker build --build-arg PROXY -f deployment/DockerfileNginx -t $DOCKER_URI .
      - echo "$DOCKER_HUB_PASSWORD" | docker login --username $DOCKER_HUB_USERNAME --password-stdin
      #- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker tag "$DOCKER_URI" "$DOCKER_PUSH_URI"
      - docker push "$DOCKER_PUSH_URI"
    size: 2x
    services: [docker-with-large-memory]     

  deploy: &deploy
    name: Deploy develop image to kube
    # deployment: production
    # trigger: manual
    script:
      - apt update -y
      - apt install python3-pip -y
      - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - export VERSION=$BITBUCKET_BRANCH-$BITBUCKET_BUILD_NUMBER
      - export NAMESPACE=development
      - export LOADBALANCER=external-lb-dev
      - export BRANCH=$BITBUCKET_BRANCH
      - sed  -e "s|#{LOADBALANCER}#|$LOADBALANCER|" -e "s|#{NAMESPACE}#|$NAMESPACE|" -e "s|#{BRANCH}#|$BRANCH|" -e "s|#{DOCKER_USERNAME}#|$DOCKER_USERNAME|" -e "s|#{DOCKER_NAME_NEXTJS}#|$DOCKER_NAME_NEXTJS|" -e "s|#{DOCKER_NAME_NGINX}#|$DOCKER_NAME_NGINX|" -e "s|#{VERSION}#|$VERSION|" k8s.tpl.yml > k8s.yml
      - echo $BRANCH $DOCKER_USERNAME $DOCKER_NAME $VERSION
      - cat k8s.yml
      - echo "$KUBERNETES_BASE64_CONFIG" | base64 --decode > config.yml
      - kubectl --kubeconfig=config.yml apply -f k8s.yml
    services:
      - docker


  deployTest: &deployTest
    name: Deploy test image to kube
    # deployment: production
    # trigger: manual
    script:
      - apt update -y
      - apt install python3-pip -y
      - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - export VERSION=$BITBUCKET_BRANCH-$BITBUCKET_BUILD_NUMBER
      - export NAMESPACE=test
      - export LOADBALANCER=external-lb-test
      - export BRANCH=$BITBUCKET_BRANCH
      - sed  -e "s|#{LOADBALANCER}#|$LOADBALANCER|" -e "s|#{NAMESPACE}#|$NAMESPACE|" -e "s|#{BRANCH}#|$BRANCH|" -e "s|#{DOCKER_USERNAME}#|$DOCKER_USERNAME|" -e "s|#{DOCKER_NAME_NEXTJS}#|$DOCKER_NAME_NEXTJS|" -e "s|#{DOCKER_NAME_NGINX}#|$DOCKER_NAME_NGINX|" -e "s|#{VERSION}#|$VERSION|" k8s.tpl.yml > k8s.yml
      - echo $BRANCH $DOCKER_USERNAME $DOCKER_NAME $VERSION
      - cat k8s.yml
      - echo "$KUBERNETES_BASE64_CONFIG" | base64 --decode > config.yml
      - kubectl --kubeconfig=config.yml apply -f k8s.yml
    services:
      - docker

pipelines:
  branches:
    develop:
      - step: *buildImageNextjs
      - step: *buildImageNginx
      - step: *deploy
    test:
      - step: *buildImageNextjs
      - step: *buildImageNginx
      - step: *deployTest