version: '3.4'
services:
  bnpl-nextjs:
    container_name: bnpl-nextjs
    build:
      context: .
      dockerfile: deployment/DockerfileNextjs
      args:
        ENVIRONMENT: develop
    ports:
      - '3000:3000'

    stdin_open: true
    restart: on-failure
    networks:
      - dpw-network

  bnpl-nginx:
    container_name: digital-products-nginx
    build:
      context: .
      dockerfile: deployment/DockerfileNginx
      args:
        PROXY: "bnpl-nextjs:3000"
    ports:
      - '3081:443'
      - '3080:80'

    stdin_open: true
    restart: on-failure
    networks:
      - dpw-network
    depends_on:
      - bnpl-nextjs

networks:
  dpw-network:
    name: dpw-network
    driver: bridge
