####################################
#      Front Nextjs Deployment     #
####################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: difierelo-nextjs
  namespace: #{NAMESPACE}#
spec:
  replicas: 1
  selector:
    matchLabels:
      app: difierelo-nextjs
  template:
    metadata:
      labels:
        app: difierelo-nextjs
    spec:
      imagePullSecrets: # if using a private image
      - name: dockerhub-user
      containers:
      - name: difierelo-nextjs
        image: #{DOCKER_USERNAME}#/#{DOCKER_NAME_NEXTJS}#:#{VERSION}#
        env:
        - name: "ENVIRONMENT"
          value: "#{BRANCH}#"
        ports:
        - containerPort: 4200
---

###################################
#      Front Nginx Deployment     #
###################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: difierelo-nginx
  namespace: #{NAMESPACE}#
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #{LOADBALANCER}#
  template:
    metadata:
      labels:
        app: #{LOADBALANCER}#
    spec:
      imagePullSecrets: # if using a private image
      - name: dockerhub-user
      containers:
      - name: difierelo-nginx
        image: #{DOCKER_USERNAME}#/#{DOCKER_NAME_NGINX}#:#{VERSION}#
        env:
        - name: "ENVIRONMENT"
          value: "#{BRANCH}#"
        ports:
        - containerPort: 80
          name: "3080-port"
        - containerPort: 443
          name: "3081-port"
---

#########################################
#   Expose K8S Service for nextjs       #
#########################################
apiVersion: v1
kind: Service
metadata:
 name: difierelo-nextjs-server
 namespace: #{NAMESPACE}#
spec:
 selector:
   app: difierelo-nextjs
 type: ClusterIP
 ports:
   - name: http
     port: 3000
     targetPort: 3000    
---

##########################################
#        Expose K8S Front Web App        #
##########################################
# apiVersion: v1
# kind: Service
# metadata:
#   name: productos-front-web
#   namespace: #{NAMESPACE}#
# spec:
#   selector:
#     app: productos-nginx
#   type: LoadBalancer
#   ports:
#   - name: http
#     port: 80
#     targetPort: 80
#   - name: https
#     port: 443
#     targetPort: 443
---