# Initial Steps:
# To load all projects we need run:
# - first time apply deployment/kubernetes/namespace-difierelo.yml
# - finish apply the config this file k8s.yml

#################################
#      Front Web Deployment     #
#################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: difierelo-front
  #namespace: #{NAMESPACE}#
  labels:
    app: difierelo-front
spec:
  replicas: 1
  selector:
    matchLabels:
      lbtype: external
  template:
    metadata:
      labels:
        lbtype: external
        app: difierelo-front
    spec:
      imagePullSecrets: # if using a private image
      - name: dockerhub-user
      containers:
      - name: difierelo-front
        image: #{DOCKER_USERNAME}#/#{DOCKER_NAME}#:#{VERSION}#
        env:
        - name: "ENVIRONMENT"
          value: "#{BRANCH}#"
        ports:
        - containerPort: 3000
          name: "3080-port"
        #- containerPort: 443
---

##########################################
#        Expose K8S Front Web App        #
##########################################
# apiVersion: v1
# kind: Service
# metadata:
#   name: difierelo-front-web
#   namespace: #{NAMESPACE}#
# spec:
#   selector:
#     app: difierelo-front
#   type: LoadBalancer
#   ports:
#   - name: http
#     port: 80
#     targetPort: 3000
#   - name: http-port
#     port: 4200
#     targetPort: 3000
#   # - name: https
#   #   port: 443
#   #   targetPort: 443
# ---